<?php

/**
* Implements hook_menu()
*/
function students_array() {
  return array(
    'admin/content/count' => array(
      'title' => 'UN HAbitat count',
      'route_name' => 'count_list',
    ),
    // 'admin/content/count/add' => array(
    //   'title' => 'Student Add',
    //   'route_name' => 'students_add',
    // ),
    // 'admin/content/count/delete/%' => array(
    //   'title' => 'Delete Student',
    //   'route_name' => 'students_delete',
    // ),
  );
}

/**
 * Implements hook_permission()
 */
/*function students_permission() {
  return array(
    'manage students forms' => array(
      'title' => t('Manage students form submissions'),
    ),
    'use students form' => array(
      'title' => t('Use the students form'),
    ),
  );
}*/
